apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-crm
  template:
    metadata:
      labels:
        app: core-crm
    spec:
      containers:
        - name: core-crm
          image: core-crm:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: core-crm-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10